name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - run: npm ci
      - run: node app

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  set-env-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "PORT=4040" >> $GITHUB_ENV
          echo "MONGO_URI=mongodb+srv://asedqiq8:c1mMenncxGYc81eq@cluster0.tpjatzz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0" >> $GITHUB_ENV
          echo "JWT_SECRET=mykey" >> $GITHUB_ENV
          echo "ADMIN_USERNAME=Ahmed" >> $GITHUB_ENV
          echo "ADMIN_PASSWORD=Ahmed" >> $GITHUB_ENV
